### PR TITLE
Reorganized README.md

### PR DESCRIPTION
**Pull request by devinrhode2**
I'd like to add a little stronger call to action at the end of the setup steps, Does `npm run start` print out of url to open in the browser? It'd be nice to explicitly say in the readme "Then open up http://localhost:8000"

I guess I'll find out in a minute.. :)

Feel free to further edit my edits Mukesh :)

### CODE REVIEW

**Comment by devinrhode2** [comment]
making some more edits..

**Comment by devinrhode2** [comment]
I feel we should linkify the default packages list or somehow make it easy for people to reference the docs. I wonder if there's be some sort of ide integration that could put elm package docs right at your fingertips

I feel it'd be best to be integrated with reactor. Don't know how tho.

**Comment by devinrhode2** [comment]
no more edits, see final version here https://github.com/devinrhode2/frolic/tree/patch-2

**Comment by devinrhode2** [comment]
Hey Mukesh, so I didn't know this was a local electron app!

I'm going to go through [evans examples](https://github.com/evancz/elm-architecture-tutorial), and want to see things in chrome with the web inspector and elm-reactor and edit with a real editor with elm support

It'd be great if frolic could bake in lots of examples. Learning a new language I need to be able to easily go through lots of examples.

It would be cool maybe if you could bake in https://github.com/carteb/carte-blanche, maybe shape frolic as a nice isolated component fiddle-dev environment. I think I'd probably use it for that, but I'd rather just load the local app in a browser instead of electron

hope this helps! I couldn't give feedback if you hadn't made this in the first place! :)

**Comment by mukeshsoni** [comment]
Thanks for the feedback and the pull request. Appreciate it.

Loading [evans examples](https://github.com/evancz/elm-architecture-tutorial) in frolic should work seamlessly. Let me know if you are facing any issues there.

Baking examples in the app itself is in the roadmap. Checkout ideas on `lessons` in the TODO file.
Also checkout my repo on [Elm 99 problems](https://github.com/mukeshsoni/elm-99-problems-for-frolic) where i am creating the playground files for elm 99 problems. Loading any of the problem in frolic should automatically set you up with many examples function calls. All the user needs to do is fill in the function details.

Don't want to go carte-blanche route because that's aimed more towards productions applications which need a living styleguide, while frolic is inspired more by [haskellformac](http://haskellformac.com/) and is for absolute beginners to the language, teachers (screencasters?), and people who want to do some rapid prototyping.

**Pull request merged**
